## Classification Metrics (Multi-Class Classification)

`Multi-class classification metrics` are used to **evaluate models that predict
more than two classes** (for example: digits 0–9, multiple product categories,
or different disease types).

These metrics extend binary metrics to handle **multiple classes fairly**.

---

### Accuracy

**What it is**  
Accuracy measures the proportion of correctly classified samples
across all classes.

**Why it is used**
- Simple overall performance measure

**When it performs well**
- When classes are balanced

**When it performs poorly**
- When classes are imbalanced

**Key point**
- High accuracy can hide poor performance on minority classes

---

### Precision (Macro / Micro / Weighted)

**What it is**  
Precision measures how correct the model’s positive predictions are
for each class.

**Why it is used**
- Helps understand false positive behavior per class

**Types**
- **Macro Precision**: Average precision across classes (treats all classes equally)
- **Micro Precision**: Global precision across all samples
- **Weighted Precision**: Accounts for class imbalance

**Key point**
- Macro is best when all classes are equally important

---

### Recall (Macro / Micro / Weighted)

**What it is**  
Recall measures how many actual samples of each class are correctly identified.

**Why it is used**
- Important when missing a class is costly

**Types**
- **Macro Recall**: Equal importance to all classes
- **Micro Recall**: Overall recall
- **Weighted Recall**: Considers class frequency

**Key point**
- High recall means fewer missed samples per class

---

### F1 Score (Macro / Micro / Weighted)

**What it is**  
F1 Score combines precision and recall into a single metric.

**Why it is used**
- Useful when data is imbalanced
- Balances false positives and false negatives

**Types**
- **Macro F1**: Equal weight to all classes
- **Micro F1**: Global balance
- **Weighted F1**: Considers class distribution

**Key point**
- Macro F1 is preferred when minority classes matter

---

### Confusion Matrix (Multi-Class)

**What it is**  
A Confusion Matrix for multi-class problems is a table where:
- Rows represent actual classes
- Columns represent predicted classes

**Why it is used**
- Shows which classes are confused with each other
- Helps diagnose model weaknesses

**When it performs well**
- Error analysis
- Model debugging

**Key point**
- Foundation for all multi-class metrics

---

### When Multi-Class Metrics Perform Well

- Dataset has multiple categories
- Class-wise evaluation is important
- Model behavior needs detailed analysis

---

### When They Perform Poorly

- When interpreted only using accuracy
- When class imbalance is ignored
- When macro vs micro choice is incorrect

---

### Key Takeaways

- Accuracy alone is not enough for multi-class problems  
- Precision, Recall, and F1 should be averaged properly  
- Macro metrics treat all classes equally  
- Confusion Matrix gives the clearest error breakdown  
- Always choose metrics based on the problem goal

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv("../iris.csv")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [6]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['species'] = encoder.fit_transform(df['species'])

In [7]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=1)

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [10]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [11]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

DecisionTreeClassifier()

In [12]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [13]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9666666666666667
Accuracy of Decision Trees 0.9666666666666667

In [14]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,3)))

Logistic Regression Confusion Matrix

    0   1  2
0  11   0  0
1   0  12  1
2   0   0  6

In [15]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,3)))

Decision Tree Confusion Matrix

    0   1  2
0  11   0  0
1   0  12  1
2   0   0  6

In [16]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2
result.sample(10)

     Actual Label  Logistic Regression Prediction  Decision Tree Prediction
66              1                               1                         1
42              0                               0                         0
44              0                               0                         0
56              1                               1                         1
73              1                               1                         1
19              0                               0                         0
40              0                               0                         0
78              1                               1                         1
141             2                               2                         2
51              1                               1                         1

In [17]:
from sklearn.metrics import precision_score,recall_score
precision_score(y_test,y_pred1,average=None)

array([1.        , 1.        , 0.85714286])

In [18]:
recall_score(y_test,y_pred1,average=None)

array([1.        , 0.92307692, 1.        ])